In [1]:
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:11
🔁 Restarting kernel...


In [1]:
!conda install pandas numpy

Channels:
 - conda-forge
Platform: linux-64
Solving environment: - \ | done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - numpy
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2025.8.3   |       hbd8a1cb_0         151 KB  conda-forge
    certifi-2025.8.3           |     pyhd8ed1ab_0         155 KB  conda-forge
    conda-24.11.3              |  py311h38be061_0         1.1 MB  conda-forge
    libblas-3.9.0              |31_h59b9bed_openblas          16 KB  conda-forge
    libcblas-3.9.0             |31_he106b2a_openblas          16 KB  conda-forge
    libgfortran-14.2.0         |       h69a702a_2          52 KB  conda-forge
    libgfortran5-14.2.0        |       hf1ad2bd_2         1.4 MB  conda-forge
    liblapack-3.9.0            |31_h7ac8fdf_openblas          16 KB  conda-forge
    libopenblas-0.3.29         |

In [2]:
import pandas as pd
import numpy as np

In [3]:
float_data=pd.Series([1.2,-3.5,np.nan,0])

In [4]:
float_data

,0
0,1.2
1,-3.5
2,NaN
3,0.0


In [5]:
float_data.isna()

,0
0,False
1,False
2,True
3,False


In [6]:
string_data=pd.Series(["aardvark",np.nan,None,"avocado"])

In [7]:
string_data

,0
0,aardvark
1,NaN
2,None
3,avocado


In [8]:
string_data.isna()

,0
0,False
1,True
2,True
3,False


In [9]:
float_data=pd.Series([1,2,None],dtype="float64")

In [10]:
float_data

,0
0,1.0
1,2.0
2,NaN


In [11]:
float_data.isna()

,0
0,False
1,False
2,True


In [12]:
data=pd.Series([1,np.nan,3.5,np.nan,7])

In [13]:
data

,0
0,1.0
1,NaN
2,3.5
3,NaN
4,7.0


In [14]:
data.dropna()

,0
0,1.0
2,3.5
4,7.0


In [15]:
data=pd.DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3.]])

In [16]:
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [17]:
data.dropna()

,0,1,2
0,1.0,6.5,3.0


In [18]:
data.dropna(how="all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


In [19]:
data[4]=np.nan

In [20]:
data

,0,1,2,4
0,1.0,6.5,3.0,NaN
1,1.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,6.5,3.0,NaN


In [21]:
data.dropna(axis="columns",how="all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [22]:
df=pd.DataFrame(np.random.standard_normal((7,3)))

In [23]:
df

,0,1,2
0,-0.013863,0.819125,-0.840995
1,-1.237416,-0.088704,0.504603
2,-0.247322,-0.779310,-0.182426
3,0.784629,-0.784044,0.038421
4,-0.001003,0.677450,-0.179783
5,0.746981,-1.030509,0.277341
6,1.848128,-0.672410,1.611878


In [24]:
df.iloc[:4,1]=np.nan

In [25]:
df

,0,1,2
0,-0.013863,NaN,-0.840995
1,-1.237416,NaN,0.504603
2,-0.247322,NaN,-0.182426
3,0.784629,NaN,0.038421
4,-0.001003,0.677450,-0.179783
5,0.746981,-1.030509,0.277341
6,1.848128,-0.672410,1.611878


In [26]:
df.iloc[:2,2]=np.nan

In [27]:
df

,0,1,2
0,-0.013863,NaN,NaN
1,-1.237416,NaN,NaN
2,-0.247322,NaN,-0.182426
3,0.784629,NaN,0.038421
4,-0.001003,0.677450,-0.179783
5,0.746981,-1.030509,0.277341
6,1.848128,-0.672410,1.611878


In [28]:
df.dropna()

,0,1,2
4,-0.001003,0.677450,-0.179783
5,0.746981,-1.030509,0.277341
6,1.848128,-0.672410,1.611878


In [29]:
df.dropna(thresh=2)

,0,1,2
2,-0.247322,NaN,-0.182426
3,0.784629,NaN,0.038421
4,-0.001003,0.677450,-0.179783
5,0.746981,-1.030509,0.277341
6,1.848128,-0.672410,1.611878


In [30]:
df.fillna(0)

,0,1,2
0,-0.013863,0.000000,0.000000
1,-1.237416,0.000000,0.000000
2,-0.247322,0.000000,-0.182426
3,0.784629,0.000000,0.038421
4,-0.001003,0.677450,-0.179783
5,0.746981,-1.030509,0.277341
6,1.848128,-0.672410,1.611878


In [31]:
df.fillna({1:0.5,2:0})

,0,1,2
0,-0.013863,0.500000,0.000000
1,-1.237416,0.500000,0.000000
2,-0.247322,0.500000,-0.182426
3,0.784629,0.500000,0.038421
4,-0.001003,0.677450,-0.179783
5,0.746981,-1.030509,0.277341
6,1.848128,-0.672410,1.611878


In [32]:
df=pd.DataFrame(np.random.standard_normal((6,3)))

In [33]:
df.iloc[2:,1]=np.nan

In [34]:
df.iloc[4:,2]=np.nan

In [35]:
df

,0,1,2
0,-0.453781,0.282313,0.464359
1,-2.613323,1.990697,-0.490272
2,0.734462,NaN,-1.353378
3,0.305571,NaN,-0.386780
4,-0.838261,NaN,NaN
5,-2.098433,NaN,NaN


In [36]:
df.fillna(method="ffill")

/tmp/ipython-input-3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


,0,1,2
0,-0.453781,0.282313,0.464359
1,-2.613323,1.990697,-0.490272
2,0.734462,1.990697,-1.353378
3,0.305571,1.990697,-0.386780
4,-0.838261,1.990697,-0.386780
5,-2.098433,1.990697,-0.386780


In [37]:
df.fillna(method="ffill",limit=2)

/tmp/ipython-input-3768739427.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill",limit=2)


,0,1,2
0,-0.453781,0.282313,0.464359
1,-2.613323,1.990697,-0.490272
2,0.734462,1.990697,-1.353378
3,0.305571,1.990697,-0.386780
4,-0.838261,NaN,-0.386780
5,-2.098433,NaN,-0.386780


In [38]:
data=pd.Series([1.,np.nan,3.5,np.nan,7])

In [39]:
data.mean()

np.float64(3.8333333333333335)

In [40]:
data.fillna(data.mean())

,0
0,1.000000
1,3.833333
2,3.500000
3,3.833333
4,7.000000


In [41]:
data.sum()

np.float64(11.5)

In [42]:
data=pd.DataFrame({"k1":["one","two"]*3+["two"],
                   "k2":[1,1,2,3,3,4,4]})

In [43]:
data

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [44]:
data.duplicated()

,0
0,False
1,False
2,False
3,False
4,False
5,False
6,True


In [45]:
data.drop_duplicates()

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


In [46]:
data["v1"]=range(7)

In [47]:
data

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [48]:
data.drop_duplicates(subset=["k1"])

,k1,k2,v1
0,one,1,0
1,two,1,1


In [49]:
data.drop_duplicates(subset=["k1","k2"],keep="last")

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
6,two,4,6


In [50]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon","pastrami", "corned beef", "bacon","pastrami", "honey ham", "nova lox"],"ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [51]:
data

,food,ounces
0,bacon,4.0
1,pulled pork,3.0
2,bacon,12.0
3,pastrami,6.0
4,corned beef,7.5
5,bacon,8.0
6,pastrami,3.0
7,honey ham,5.0
8,nova lox,6.0


In [52]:
meat_to_animal = {
"bacon": "pig",
"pulled pork": "pig",
"pastrami": "cow",
"corned beef": "cow",
"honey ham": "pig",
"nova lox": "salmon"
}

In [53]:
data["animal"]=data["food"].map(meat_to_animal)

In [54]:
def get_animal(x):
  return meat_to_animal[x]

In [55]:
data["food"].map(get_animal)

,food
0,pig
1,pig
2,pig
3,cow
4,cow
5,pig
6,cow
7,pig
8,salmon


In [56]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [57]:
data

,0
0,1.0
1,-999.0
2,2.0
3,-999.0
4,-1000.0
5,3.0


In [58]:
data.replace(-999,np.nan)

,0
0,1.0
1,NaN
2,2.0
3,NaN
4,-1000.0
5,3.0


In [59]:
data.replace([-999,-1000],np.nan)

,0
0,1.0
1,NaN
2,2.0
3,NaN
4,NaN
5,3.0


In [60]:
data.replace([-999,-1000],[np.nan,0])

,0
0,1.0
1,NaN
2,2.0
3,NaN
4,0.0
5,3.0


In [61]:
data.replace({-999:np.nan,-1000:0})

,0
0,1.0
1,NaN
2,2.0
3,NaN
4,0.0
5,3.0


In [62]:
data=pd.DataFrame(np.arange(12).reshape((3,4)),index=["Ohio", "Colorado", "New York"],columns=["one", "two", "three", "four"])

In [63]:
def transform(x):
  return x[:4].upper()

In [64]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [65]:
data.index=data.index.map(transform)

In [66]:
data

,one,two,three,four
OHIO,0,1,2,3
COLO,4,5,6,7
NEW,8,9,10,11


In [67]:
data.rename(index=str.title,columns=str.upper)

,ONE,TWO,THREE,FOUR
Ohio,0,1,2,3
Colo,4,5,6,7
New,8,9,10,11


In [68]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [69]:
bins=[18,25,35,60,100]

In [70]:
age_categories=pd.cut(ages,bins)

In [71]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [72]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [73]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [74]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [75]:
pd.value_counts(age_categories)

/tmp/ipython-input-3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


,count
"(18, 25]",5
"(25, 35]",3
"(35, 60]",3
"(60, 100]",1


In [76]:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [77]:
group_names=["Youth","YouthAdult","MiddleAged","Senior"]

In [78]:
pd.cut(ages,bins,labels=group_names)

['Youth', 'Youth', 'Youth', 'YouthAdult', 'Youth', ..., 'YouthAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YouthAdult']
Length: 12
Categories (4, object): ['Youth' < 'YouthAdult' < 'MiddleAged' < 'Senior']

In [79]:
data=np.random.uniform(size=20)

In [80]:
pd.cut(data,4,precision=2)

[(0.51, 0.74], (0.27, 0.51], (0.037, 0.27], (0.74, 0.98], (0.037, 0.27], ..., (0.51, 0.74], (0.74, 0.98], (0.27, 0.51], (0.037, 0.27], (0.037, 0.27]]
Length: 20
Categories (4, interval[float64, right]): [(0.037, 0.27] < (0.27, 0.51] < (0.51, 0.74] <
                                           (0.74, 0.98]]

In [81]:
data=np.random.standard_normal(1000)

In [82]:
quartiles=pd.qcut(data,4,precision=2)

In [83]:
quartiles

[(-3.21, -0.74], (-3.21, -0.74], (-0.05, 0.66], (0.66, 3.24], (-0.74, -0.05], ..., (-0.05, 0.66], (0.66, 3.24], (-3.21, -0.74], (-0.74, -0.05], (-3.21, -0.74]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.21, -0.74] < (-0.74, -0.05] < (-0.05, 0.66] <
                                           (0.66, 3.24]]

In [84]:
pd.value_counts(quartiles)

/tmp/ipython-input-3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


,count
"(-3.21, -0.74]",250
"(-0.74, -0.05]",250
"(-0.05, 0.66]",250
"(0.66, 3.24]",250


In [85]:
pd.qcut(data,[0,0.1,0.5,0.9,1.]).value_counts()

,count
"(-3.197, -1.282]",100
"(-1.282, -0.0502]",400
"(-0.0502, 1.26]",400
"(1.26, 3.237]",100


In [86]:
data=pd.DataFrame(np.random.standard_normal((1000,4)))

In [87]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.017440,-0.026905,0.017016,-0.015576
std,1.010271,0.989596,0.989644,1.017400
min,-3.224367,-2.783641,-3.395348,-3.628663
25%,-0.666222,-0.710857,-0.636605,-0.692896
50%,0.004222,0.005387,0.079070,-0.010332
75%,0.679288,0.655151,0.726161,0.689375
max,3.400376,3.674821,3.076781,2.909256


In [88]:
col=data[2]

In [89]:
col[col.abs()>3]

,2
64,-3.147096
923,3.076781
961,-3.395348


In [90]:
data[(data.abs()>3).any(axis="columns")]

,0,1,2,3
64,-1.740085,-0.137980,-3.147096,0.296017
104,-3.017283,1.328299,0.936172,1.067923
245,3.400376,0.858234,0.730842,-0.869285
335,-3.224367,0.748014,1.470678,-0.173514
598,0.175901,-1.150646,0.201953,-3.628663
664,-0.342736,0.222978,-0.685483,-3.265910
785,0.301882,3.674821,-0.089869,-2.262927
923,-0.551674,-0.195940,3.076781,1.042855
945,1.659836,0.394808,0.352214,-3.121053
961,0.402710,-0.033413,-3.395348,-1.043997


In [91]:
data[data.abs()>3]=np.sign(data)*3

In [92]:
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.017281,-0.027580,0.017482,-0.014561
std,1.008259,0.987297,0.987662,1.014176
min,-3.000000,-2.783641,-3.000000,-3.000000
25%,-0.666222,-0.710857,-0.636605,-0.692896
50%,0.004222,0.005387,0.079070,-0.010332
75%,0.679288,0.655151,0.726161,0.689375
max,3.000000,3.000000,3.000000,2.909256


In [93]:
df=pd.DataFrame(np.arange(5*7).reshape((5,7)))

In [94]:
df

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27
4,28,29,30,31,32,33,34


In [95]:
sampler=np.random.permutation(5)

In [96]:
sampler

array([2, 4, 0, 1, 3])

In [97]:
df.take(sampler)

,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
3,21,22,23,24,25,26,27


In [98]:
df.iloc[sampler]

,0,1,2,3,4,5,6
2,14,15,16,17,18,19,20
4,28,29,30,31,32,33,34
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
3,21,22,23,24,25,26,27


In [99]:
column_sampler=np.random.permutation(7)

In [100]:
column_sampler

array([4, 0, 6, 3, 1, 5, 2])

In [101]:
df.take(column_sampler,axis="columns")

,4,0,6,3,1,5,2
0,4,0,6,3,1,5,2
1,11,7,13,10,8,12,9
2,18,14,20,17,15,19,16
3,25,21,27,24,22,26,23
4,32,28,34,31,29,33,30


In [102]:
df.sample(n=3)

,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34
2,14,15,16,17,18,19,20
0,0,1,2,3,4,5,6


In [103]:
choices=pd.Series([5,7,-1,6,4])

In [104]:
choices.sample(n=10,replace=True)

,0
1,7
2,-1
2,-1
2,-1
3,6
4,4
3,6
2,-1
1,7
0,5


In [105]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],"data1": range(6)})

In [106]:
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [107]:
pd.get_dummies(df["key"])

,a,b,c
0,False,True,False
1,False,True,False
2,True,False,False
3,False,False,True
4,True,False,False
5,False,True,False


In [108]:
dummies=pd.get_dummies(df["key"])

In [109]:
df_with_dummy=df[["data1"]].join(dummies)

In [110]:
df_with_dummy

,data1,a,b,c
0,0,False,True,False
1,1,False,True,False
2,2,True,False,False
3,3,False,False,True
4,4,True,False,False
5,5,False,True,False


In [111]:
mnames=["movie_id","title","geners"]

In [112]:
movies=pd.read_table("/content/drive/MyDrive/Colab Notebooks/Data/examples_of_pydata_book/datasets/movielens/movies.dat",sep="::",header=None,names=mnames,engine="python")

In [113]:
movies

,movie_id,title,geners
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama


In [114]:
dummies=movies["geners"].str.get_dummies("|")

In [115]:
dummies

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3879,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3880,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3881,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0


In [116]:
movies_windic=movies.join(dummies.add_prefix("Genre_"))

In [118]:
movies_windic.iloc[0]

,0
movie_id,1
title,Toy Story (1995)
geners,Animation|Children's|Comedy
Genre_Action,0
Genre_Adventure,0
Genre_Animation,1
Genre_Children's,1
Genre_Comedy,1
Genre_Crime,0
Genre_Documentary,0


In [119]:
np.random.seed(12345)

In [120]:
values=np.random.uniform(size=10)

In [121]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [122]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [123]:
pd.get_dummies(pd.cut(values,bins))

,"(0.0, 0.2]","(0.2, 0.4]","(0.4, 0.6]","(0.6, 0.8]","(0.8, 1.0]"
0,False,False,False,False,True
1,False,True,False,False,False
2,True,False,False,False,False
3,False,True,False,False,False
4,False,False,True,False,False
5,False,False,True,False,False
6,False,False,False,False,True
7,False,False,False,True,False
8,False,False,False,True,False
9,False,False,False,True,False


In [124]:
val = "a,b, guido"

In [125]:
val.split(",")

['a', 'b', ' guido']

In [126]:
pieces=[x.strip() for x in val.split(",")]

In [127]:
pieces

['a', 'b', 'guido']

In [128]:
first,second,third=pieces

In [129]:
first+"::"+second+"::"+third

'a::b::guido'

In [130]:
"::".join(pieces)

'a::b::guido'

In [131]:
"guido" in val

True

In [132]:
val.index(",")

1

In [133]:
val.find(":")

-1

In [134]:
val.count(",")

2

In [135]:
val.replace(",","::")

'a::b:: guido'

In [136]:
val.replace(",","")

'ab guido'

In [137]:
import re

In [138]:
text = "foo bar\t baz \tqux"

In [139]:
text

'foo bar\t baz \tqux'

In [140]:
re.split(r"\s+",text)

['foo', 'bar', 'baz', 'qux']

In [142]:
regex=re.compile(r"\s+")

In [143]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [144]:
regex.findall(text)

[' ', '\t ', ' \t']

In [145]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com","Rob": "rob@gmail.com", "Wes": np.nan}

In [146]:
data=pd.Series(data)

In [147]:
data

,0
Dave,dave@google.com
Steve,steve@gmail.com
Rob,rob@gmail.com
Wes,NaN


In [148]:
data.isna()

,0
Dave,False
Steve,False
Rob,False
Wes,True


In [150]:
data.str.contains("gmail")

,0
Dave,False
Steve,True
Rob,True
Wes,NaN


In [151]:
values = pd.Series(['apple', 'orange', 'apple','apple'] * 2)

In [152]:
values

,0
0,apple
1,orange
2,apple
3,apple
4,apple
5,orange
6,apple
7,apple


In [153]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [154]:
pd.value_counts(values)

/tmp/ipython-input-3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


,count
apple,6
orange,2


In [155]:
values = pd.Series([0, 1, 0, 0] * 2)

In [156]:
dim=pd.Series(["apple","orange"])

In [157]:
dim.take(values)

,0
0,apple
1,orange
0,apple
0,apple
0,apple
1,orange
0,apple
0,apple


In [158]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [159]:
N=len(fruits)

In [160]:
rng=np.random.default_rng(seed=12345)

In [161]:
df = pd.DataFrame({'fruit': fruits,'basket_id': np.arange(N),'count': rng.integers(3, 15, size=N),'weight': rng.uniform(0, 4, size=N)},columns=['basket_id', 'fruit', 'count', 'weight'])

In [162]:
df

,basket_id,fruit,count,weight
0,0,apple,11,1.564438
1,1,orange,5,1.331256
2,2,apple,12,2.393235
3,3,apple,6,0.746937
4,4,apple,5,2.691024
5,5,orange,12,3.767211
6,6,apple,10,0.992983
7,7,apple,11,3.795525


In [163]:
fruit_cat=df["fruit"].astype("category")

In [164]:
fruit_cat

,fruit
0,apple
1,orange
2,apple
3,apple
4,apple
5,orange
6,apple
7,apple


In [165]:
c=fruit_cat.array

In [166]:
type(c)

pandas.core.arrays.categorical.Categorical

In [167]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [168]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [170]:
rng=np.random.default_rng(seed=12345)

In [171]:
draws=rng.standard_normal(1000)

In [172]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [173]:
bins=pd.qcut(draws,4)

In [174]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [175]:
bins=pd.qcut(draws,4,labels=["Q1","Q2","Q3","Q4"])

In [176]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [177]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [178]:
bins=pd.Series(bins,name="quartile")

In [181]:
results=(pd.Series(draws).groupby(bins).agg(["count","min","max"]).reset_index())

/tmp/ipython-input-2602312380.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  results=(pd.Series(draws).groupby(bins).agg(["count","min","max"]).reset_index())


In [182]:
results

,quartile,count,min,max
0,Q1,250,-3.119609,-0.678494
1,Q2,250,-0.673305,0.008009
2,Q3,250,0.018753,0.686183
3,Q4,250,0.688282,3.211418


In [183]:
N=10_000_000

In [184]:
labels=pd.Series(["foo","bar","baz","qux"]*(N//4))

In [185]:
categories=labels.astype("category")

In [186]:
labels.memory_usage(deep=True)

520000132

In [187]:
categories.memory_usage(deep=True)

10000512

In [188]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [189]:
cat_s = s.astype('category')

In [190]:
cat_s

,0
0,a
1,b
2,c
3,d
4,a
5,b
6,c
7,d


In [191]:
cat_s.cat.codes

,0
0,0
1,1
2,2
3,3
4,0
5,1
6,2
7,3


In [193]:
cat_s.array.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [194]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [195]:
cat_s.cat.codes

,0
0,0
1,1
2,2
3,3
4,0
5,1
6,2
7,3


In [196]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [197]:
cat_s2=cat_s.cat.set_categories(actual_categories)

In [198]:
cat_s2

,0
0,a
1,b
2,c
3,d
4,a
5,b
6,c
7,d


In [200]:
cat_s.value_counts()

,count
a,2
b,2
c,2
d,2


In [201]:
cat_s2.value_counts()

,count
a,2
b,2
c,2
d,2
e,0


In [202]:
cat_s3=cat_s[cat_s.isin(["a","b"])]

In [203]:
cat_s3

,0
0,a
1,b
4,a
5,b


In [204]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [205]:
pd.get_dummies(cat_s)

,a,b,c,d
0,True,False,False,False
1,False,True,False,False
2,False,False,True,False
3,False,False,False,True
4,True,False,False,False
5,False,True,False,False
6,False,False,True,False
7,False,False,False,True
