In [1]:
import pandas as pd
import numpy as np

In [2]:
obj=pd.Series([4,7,-5,3])

In [3]:
obj

,0
0,4
1,7
2,-5
3,3


In [4]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2=pd.Series([4,7,-5,3],index=["d","b","a","c"])

In [7]:
obj2

,0
d,4
b,7
a,-5
c,3


In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2["a"]

np.int64(-5)

In [10]:
obj2[["c","a","d"]]

,0
c,3
a,-5
d,4


In [11]:
obj2[obj2>0]

,0
d,4
b,7
c,3


In [12]:
obj2*2

,0
d,8
b,14
a,-10
c,6


In [13]:
np.exp(obj2)

,0
d,54.598150
b,1096.633158
a,0.006738
c,20.085537


In [14]:
"b" in obj2

True

In [15]:
"e" in obj2

False

In [16]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [17]:
obj3=pd.Series(sdata)

In [18]:
obj3

,0
Ohio,35000
Texas,71000
Oregon,16000
Utah,5000


In [19]:
obj3

,0
Ohio,35000
Texas,71000
Oregon,16000
Utah,5000


In [20]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [21]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [22]:
obj4=pd.Series(sdata,index=states)

In [23]:
obj4

,0
California,NaN
Ohio,35000.0
Oregon,16000.0
Texas,71000.0


In [24]:
pd.isna(obj4)

,0
California,True
Ohio,False
Oregon,False
Texas,False


In [25]:
pd.notna(obj4)

,0
California,False
Ohio,True
Oregon,True
Texas,True


In [26]:
obj3+obj4

,0
California,NaN
Ohio,70000.0
Oregon,32000.0
Texas,142000.0
Utah,NaN


In [27]:
obj4.name="populartion"

In [28]:
obj4.index.name="state"

In [29]:
obj4

,populartion
state,
California,NaN
Ohio,35000.0
Oregon,16000.0
Texas,71000.0


In [30]:
obj.index=["Bob", "Steve", "Jeff", "Ryan"]

In [31]:
obj

,0
Bob,4
Steve,7
Jeff,-5
Ryan,3


In [32]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [33]:
frame=pd.DataFrame(data)

In [34]:
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [35]:
frame.head()

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [36]:
frame.tail()

,state,year,pop
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [37]:
pd.DataFrame(data,columns=["year","state","pop"])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


In [38]:
frame2=pd.DataFrame(data,columns=["year","state",'pop',"debt"])

In [39]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame2["state"]

,state
0,Ohio
1,Ohio
2,Ohio
3,Nevada
4,Nevada
5,Nevada


In [42]:
frame2.year

,year
0,2000
1,2001
2,2002
3,2001
4,2002
5,2003


In [43]:
frame.loc[1]

,1
state,Ohio
year,2001
pop,1.7


In [44]:
frame.iloc[2]

,2
state,Ohio
year,2002
pop,3.6


In [45]:
frame2["debt"]=16.5

In [46]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,16.5
1,2001,Ohio,1.7,16.5
2,2002,Ohio,3.6,16.5
3,2001,Nevada,2.4,16.5
4,2002,Nevada,2.9,16.5
5,2003,Nevada,3.2,16.5


In [47]:
frame2["debt"]=np.arange(6.)

In [48]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,0.0
1,2001,Ohio,1.7,1.0
2,2002,Ohio,3.6,2.0
3,2001,Nevada,2.4,3.0
4,2002,Nevada,2.9,4.0
5,2003,Nevada,3.2,5.0


In [49]:
val=pd.Series([-1.2,-1.5,-1.5],index=["two","four","five"])

In [50]:
frame2["debt"]=val

In [51]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [52]:
frame2["eastern"]=frame2["state"]=="Ohio"

In [53]:
frame2

,year,state,pop,debt,eastern
0,2000,Ohio,1.5,NaN,True
1,2001,Ohio,1.7,NaN,True
2,2002,Ohio,3.6,NaN,True
3,2001,Nevada,2.4,NaN,False
4,2002,Nevada,2.9,NaN,False
5,2003,Nevada,3.2,NaN,False


In [54]:
del frame2["eastern"]

In [55]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [56]:
populations={"Ohio":{2000:1.5,2001:1.7,2002:3.6,},"Nevada": {2001: 2.4, 2002: 2.9}}

In [57]:
frame3=pd.DataFrame(populations)

In [58]:
frame3

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [59]:
frame3.T

,2000,2001,2002
Ohio,1.5,1.7,3.6
Nevada,NaN,2.4,2.9


In [60]:
pd.DataFrame(populations,index=[2001,2002,2003])

,Ohio,Nevada
2001,1.7,2.4
2002,3.6,2.9
2003,NaN,NaN


In [61]:
pdata={"Ohio":frame3["Ohio"][:-1],
       "Nevada":frame3['Nevada'][:2]}

In [62]:
pd.DataFrame(pdata)

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4


In [63]:
frame3.index.name="year"
frame3.columns.name="state"

In [64]:
frame3

state,Ohio,Nevada
year,,
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [65]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [66]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [67]:
obj=pd.Series(np.arange(3),index=["a","b","c"])

In [68]:
index=obj.index

In [69]:
index

Index(['a', 'b', 'c'], dtype='object')

In [70]:
index[1:]

Index(['b', 'c'], dtype='object')

In [71]:
labels=pd.Index(np.arange(3))

In [72]:
labels

Index([0, 1, 2], dtype='int64')

In [73]:
obj2=pd.Series([1.5,-2.5,0],index=labels)

In [74]:
obj2

,0
0,1.5
1,-2.5
2,0.0


In [75]:
obj2.index is labels

True

In [76]:
frame3

state,Ohio,Nevada
year,,
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [77]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [78]:
"Ohio" in frame3.columns

True

In [79]:
2003 in frame3.index

False

In [80]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [81]:
obj

,0
d,4.5
b,7.2
a,-5.3
c,3.6


In [82]:
obj2=obj.reindex(["a","b","c","d","e"])

In [83]:
obj2

,0
a,-5.3
b,7.2
c,3.6
d,4.5
e,NaN


In [84]:
obj3=pd.Series(["blue","pruple","yellow"],index=[0,2,4])

In [85]:
obj3

,0
0,blue
2,pruple
4,yellow


In [86]:
obj3.reindex(np.arange(6),method='ffill')

,0
0,blue
1,blue
2,pruple
3,pruple
4,yellow
5,yellow


In [87]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),index=["a","c","d"],columns=["Ohio","Texas","California"])

In [88]:
frame

,Ohio,Texas,California
a,0,1,2
c,3,4,5
d,6,7,8


In [89]:
frame2=frame.reindex(index=["a","b","c","d"])

In [90]:
frame2

,Ohio,Texas,California
a,0.0,1.0,2.0
b,NaN,NaN,NaN
c,3.0,4.0,5.0
d,6.0,7.0,8.0


In [91]:
states=["Texas","Utah","California"]

In [92]:
frame.reindex(columns=states)

,Texas,Utah,California
a,1,NaN,2
c,4,NaN,5
d,7,NaN,8


In [93]:
frame

,Ohio,Texas,California
a,0,1,2
c,3,4,5
d,6,7,8


In [94]:
frame.loc[["a","d","c"],["California","Texas"]]

,California,Texas
a,2,1
d,8,7
c,5,4


In [95]:
obj=pd.Series(np.arange(5.),index=["a","b","c","d","e"])

In [96]:
obj

,0
a,0.0
b,1.0
c,2.0
d,3.0
e,4.0


In [97]:
new_obj=obj.drop("c")

In [98]:
new_obj

,0
a,0.0
b,1.0
d,3.0
e,4.0


In [99]:
obj.drop(["d","c"])

,0
a,0.0
b,1.0
e,4.0


In [100]:
data=pd.DataFrame(np.arange(16).reshape(4,4),index=["Ohio","Colorado","Utah","New York"],columns=["one","two","three","four"])

In [101]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [102]:
data.drop(index=["Colorado","Ohio"])

,one,two,three,four
Utah,8,9,10,11
New York,12,13,14,15


In [103]:
data.drop(columns=["two"])

,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


In [104]:
data.drop("two",axis=1)

,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


In [105]:
data.drop(["two","four"],axis="columns")

,one,three
Ohio,0,2
Colorado,4,6
Utah,8,10
New York,12,14


In [106]:
obj=pd.Series(np.arange(4.),index=["a","b","c","d"])

In [107]:
obj

,0
a,0.0
b,1.0
c,2.0
d,3.0


In [108]:
obj["b"]

np.float64(1.0)

In [109]:
obj[1]

/tmp/ipython-input-2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


np.float64(1.0)

In [110]:
obj[2:4]

,0
c,2.0
d,3.0


In [111]:
obj[["b","a","d"]]

,0
b,1.0
a,0.0
d,3.0


In [112]:
obj<2

,0
a,True
b,True
c,False
d,False


In [113]:
obj[obj<2]

,0
a,0.0
b,1.0


In [114]:
obj.loc[["b","a","d"]]

,0
b,1.0
a,0.0
d,3.0


In [115]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [116]:
data["two"]

,two
Ohio,1
Colorado,5
Utah,9
New York,13


In [117]:
data[["three","one"]]

,three,one
Ohio,2,0
Colorado,6,4
Utah,10,8
New York,14,12


In [118]:
data[:2]

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7


In [119]:
data[data["three"]>5]

,one,two,three,four
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [120]:
data<5

,one,two,three,four
Ohio,True,True,True,True
Colorado,True,False,False,False
Utah,False,False,False,False
New York,False,False,False,False


In [121]:
data[data<5]=0

In [122]:
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [123]:
data.loc["Colorado"]

,Colorado
one,0
two,5
three,6
four,7


In [124]:
data.loc[["Colorado","New York"]]

,one,two,three,four
Colorado,0,5,6,7
New York,12,13,14,15


In [125]:
data.loc["Colorado",["two","three"]]

,Colorado
two,5
three,6


In [126]:
data.iloc[2]

,Utah
one,8
two,9
three,10
four,11


In [127]:
data.iloc[[2,1]]

,one,two,three,four
Utah,8,9,10,11
Colorado,0,5,6,7


In [128]:
data.iloc[2,[3,0,1]]

,Utah
four,11
one,8
two,9


In [129]:
data.iloc[[2,1],[3,0,1]]

,four,one,two
Utah,11,8,9
Colorado,7,0,5


In [130]:
data.loc[:"Utah","two"]

,two
Ohio,0
Colorado,5
Utah,9


In [131]:
data.iloc[:,:3]

,one,two,three
Ohio,0,0,0
Colorado,0,5,6
Utah,8,9,10
New York,12,13,14


In [132]:
data.iloc[:,:3][data.three>5]

,one,two,three
Colorado,0,5,6
Utah,8,9,10
New York,12,13,14


In [133]:
data.loc[data.three>=2]

,one,two,three,four
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [134]:
ser=pd.Series(np.arange(3.))

In [135]:
ser

,0
0,0.0
1,1.0
2,2.0


In [136]:
ser2=pd.Series(np.arange(3.),index=["a","b","c"])

In [137]:
ser2[-1]

/tmp/ipython-input-811950851.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


np.float64(2.0)

In [138]:
ser.iloc[-1]

np.float64(2.0)

In [139]:
ser[:2]

,0
0,0.0
1,1.0


In [140]:
data.loc[:,"one"]=1

In [141]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,1,5,6,7
Utah,1,9,10,11
New York,1,13,14,15


In [142]:
data.iloc[2]=5

In [143]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,1,5,6,7
Utah,5,5,5,5
New York,1,13,14,15


In [144]:
data.loc[data["four"]>5]=3

In [145]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,5,5
New York,3,3,3,3


In [146]:
data.loc[data.three == 5]["three"]

,three
Utah,5


In [147]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list("abcd"))

In [148]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list("abcde"))

In [149]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,6.0,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [150]:
df2.loc[1,"b"]=np.nan

In [151]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,NaN,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [152]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [153]:
df1+df2

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,NaN
1,9.0,NaN,13.0,15.0,NaN
2,18.0,20.0,22.0,24.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [154]:
df1.add(df2,fill_value=0)

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,4.0
1,9.0,5.0,13.0,15.0,9.0
2,18.0,20.0,22.0,24.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [155]:
1/df1

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [156]:
df1.rdiv(1)

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [157]:
df1.reindex(columns=df2.columns,fill_value=0)

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,0
1,4.0,5.0,6.0,7.0,0
2,8.0,9.0,10.0,11.0,0


In [158]:
arr=np.arange(12.).reshape((3,4))

In [159]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [160]:
arr[0]

array([0., 1., 2., 3.])

In [161]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [162]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                   columns=list("bde"),
                   index=["Utah","Ohio","Texas","Oregon"])

In [163]:
series=frame.iloc[0]

In [164]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [165]:
series

,Utah
b,0.0
d,1.0
e,2.0


In [166]:
frame-series

,b,d,e
Utah,0.0,0.0,0.0
Ohio,3.0,3.0,3.0
Texas,6.0,6.0,6.0
Oregon,9.0,9.0,9.0


In [167]:
series2=pd.Series(np.arange(3),index=["b","e","f"])

In [168]:
series2

,0
b,0
e,1
f,2


In [169]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [170]:
frame+series2

,b,d,e,f
Utah,0.0,NaN,3.0,NaN
Ohio,3.0,NaN,6.0,NaN
Texas,6.0,NaN,9.0,NaN
Oregon,9.0,NaN,12.0,NaN


In [171]:
series3=frame["d"]

In [172]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [173]:
series3=frame["d"]

In [174]:
series3

,d
Utah,1.0
Ohio,4.0
Texas,7.0
Oregon,10.0


In [175]:
frame

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [176]:
frame.sub(series3,axis="index")

,b,d,e
Utah,-1.0,0.0,1.0
Ohio,-1.0,0.0,1.0
Texas,-1.0,0.0,1.0
Oregon,-1.0,0.0,1.0


In [177]:
frame=pd.DataFrame(np.random.standard_normal((4,3)),
                   columns=list("bde"),
                   index=["Utah","Ohio","Texas","Oregon"],)

In [178]:
frame

,b,d,e
Utah,-1.502832,2.427927,0.468308
Ohio,0.259267,-0.784293,-1.291045
Texas,-0.430291,0.992249,0.588659
Oregon,-0.755728,1.084758,-1.505012


In [179]:
np.abs(frame)

,b,d,e
Utah,1.502832,2.427927,0.468308
Ohio,0.259267,0.784293,1.291045
Texas,0.430291,0.992249,0.588659
Oregon,0.755728,1.084758,1.505012


In [180]:
def f1(x):
  return x.max()-x.min()

In [181]:
frame.apply(f1)

,0
b,1.762100
d,3.212221
e,2.093672


In [182]:
frame.apply(f1,axis="columns")

,0
Utah,3.930760
Ohio,1.550312
Texas,1.422539
Oregon,2.589770


In [183]:
def f2(x):
  return pd.Series([x.min(),x.max()],index=["min","max"])

In [184]:
frame.apply(f2)

,b,d,e
min,-1.502832,-0.784293,-1.505012
max,0.259267,2.427927,0.588659


In [185]:
def my_format(x):
  return f"{x:.2f}"

In [186]:
frame.applymap(my_format)

/tmp/ipython-input-1462544007.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)


,b,d,e
Utah,-1.50,2.43,0.47
Ohio,0.26,-0.78,-1.29
Texas,-0.43,0.99,0.59
Oregon,-0.76,1.08,-1.51


In [187]:
obj=pd.Series(np.arange(4),index=["d","a","b","c"])

In [188]:
obj

,0
d,0
a,1
b,2
c,3


In [189]:
obj.sort_index()

,0
a,1
b,2
c,3
d,0


In [190]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),
                   index=["three","one"],
                   columns=["d","a","b","c"])

In [191]:
frame

,d,a,b,c
three,0,1,2,3
one,4,5,6,7


In [192]:
frame.sort_index()

,d,a,b,c
one,4,5,6,7
three,0,1,2,3


In [193]:
frame.sort_index(axis="columns")

,a,b,c,d
three,1,2,3,0
one,5,6,7,4


In [194]:
frame.sort_index(axis="columns",ascending=False)

,d,c,b,a
three,0,3,2,1
one,4,7,6,5


In [195]:
obj=pd.Series([4,7,-3,2])

In [196]:
obj.sort_values()

,0
2,-3
3,2
0,4
1,7


In [197]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

In [198]:
obj

,0
0,4.0
1,NaN
2,7.0
3,NaN
4,-3.0
5,2.0


In [199]:
obj.sort_values()

,0
4,-3.0
5,2.0
0,4.0
2,7.0
1,NaN
3,NaN


In [200]:
obj.sort_values(na_position='first')

,0
1,NaN
3,NaN
4,-3.0
5,2.0
0,4.0
2,7.0


In [201]:
frame=pd.DataFrame({"b":[4,7,-3,2],"a":[0,1,0,1]})

In [202]:
frame

,b,a
0,4,0
1,7,1
2,-3,0
3,2,1


In [203]:
frame.sort_values("b")

,b,a
2,-3,0
3,2,1
0,4,0
1,7,1


In [204]:
frame.sort_values(["a","b"])

,b,a
2,-3,0
0,4,0
3,2,1
1,7,1


In [205]:
obj=pd.Series([7,-5,7,4,2,0,4])

In [206]:
obj.rank()

,0
0,6.5
1,1.0
2,6.5
3,4.5
4,3.0
5,2.0
6,4.5


In [207]:
obj.rank(method="first")

,0
0,6.0
1,1.0
2,7.0
3,4.0
4,3.0
5,2.0
6,5.0


In [208]:
obj.rank(ascending=False)

,0
0,1.5
1,7.0
2,1.5
3,3.5
4,5.0
5,6.0
6,3.5


In [209]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],"c": [-2, 5, 8, -2.5]})

In [210]:
frame

,b,a,c
0,4.3,0,-2.0
1,7.0,1,5.0
2,-3.0,0,8.0
3,2.0,1,-2.5


In [211]:
frame.rank(axis="columns")

,b,a,c
0,3.0,2.0,1.0
1,3.0,1.0,2.0
2,1.0,2.0,3.0
3,3.0,2.0,1.0


In [212]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [213]:
obj

,0
a,0
a,1
b,2
b,3
c,4


In [214]:
obj.index.is_unique

False

In [215]:
obj["a"]

,0
a,0
a,1


In [216]:
obj["c"]

np.int64(4)

In [217]:
df=pd.DataFrame(np.random.standard_normal((5,3)),
                index=["a","a","b","b","c"])

In [218]:
df

,0,1,2
a,-0.870373,-1.978306,0.300683
a,0.797081,-0.061974,-0.303991
b,-0.648855,-0.287911,-0.128864
b,-1.175212,-0.581806,0.031702
c,0.857227,1.088007,-0.501729


In [219]:
df.loc["b"]

,0,1,2
b,-0.648855,-0.287911,-0.128864
b,-1.175212,-0.581806,0.031702


In [220]:
df.loc["c"]

,c
0,0.857227
1,1.088007
2,-0.501729


In [221]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
                index=list("abcd"),
                columns=["one","two"])

In [222]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [223]:
df.sum()

,0
one,9.25
two,-5.80


In [224]:
df.sum(axis="columns")

,0
a,1.40
b,2.60
c,0.00
d,-0.55


In [225]:
df.sum(skipna=False)

,0
one,NaN
two,NaN


In [226]:
df.sum(axis="columns",skipna=False)

,0
a,NaN
b,2.60
c,NaN
d,-0.55


In [227]:
df.mean(axis="columns")

,0
a,1.400
b,1.300
c,NaN
d,-0.275


In [228]:
df.idxmax()

,0
one,b
two,d


In [229]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [230]:
df.cumsum()

,one,two
a,1.40,NaN
b,8.50,-4.5
c,NaN,NaN
d,9.25,-5.8


In [231]:
df.describe()

,one,two
count,3.000000,2.000000
mean,3.083333,-2.900000
std,3.493685,2.262742
min,0.750000,-4.500000
25%,1.075000,-3.700000
50%,1.400000,-2.900000
75%,4.250000,-2.100000
max,7.100000,-1.300000


In [232]:
obj=pd.Series(["a","a","b","c"]*4)

In [233]:
obj

,0
0,a
1,a
2,b
3,c
4,a
5,a
6,b
7,c
8,a
9,a


In [234]:
obj.describe()

,0
count,16
unique,3
top,a
freq,8


In [235]:
df.prod()

,0
one,7.455
two,5.850


In [236]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [237]:
uniques=obj.unique()

In [238]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [240]:
obj.value_counts()

,count
c,3
a,3
b,2
d,1


In [241]:
pd.value_counts(obj.to_numpy(),sort=False)

/tmp/ipython-input-2733622681.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(),sort=False)


,count
c,3
a,3
d,1
b,2


In [242]:
mask=obj.isin(["b","c"])

In [243]:
mask

,0
0,True
1,False
2,False
3,False
4,False
5,True
6,True
7,True
8,True


In [244]:
obj[mask]

,0
0,c
5,b
6,b
7,c
8,c


In [245]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [246]:
unique_vals=pd.Series(["c","b","a"])

In [247]:
indices=pd.Index(unique_vals).get_indexer(to_match)

In [248]:
indices

array([0, 2, 1, 1, 0, 2])

In [249]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],"Qu2": [2, 3, 1, 2, 3],"Qu3": [1, 5, 2, 4, 4]})

In [250]:
data

,Qu1,Qu2,Qu3
0,1,2,1
1,3,3,5
2,4,1,2
3,3,2,4
4,4,3,4


In [251]:
data["Qu1"].value_counts().sort_index()

,count
Qu1,
1,1
3,2
4,2


In [253]:
result=data.apply(pd.value_counts).fillna(0)

/tmp/ipython-input-4089501022.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result=data.apply(pd.value_counts).fillna(0)


In [254]:
result

,Qu1,Qu2,Qu3
1,1.0,1.0,1.0
2,0.0,2.0,1.0
3,2.0,2.0,0.0
4,2.0,0.0,2.0
5,0.0,0.0,1.0
